// Generated by CoffeeScript 1.6.3
(function() {
  var gm, Thumbbot, exec, googleImages;

  Magician = require('gm');

  googleImages = require('google-images');

  exec = require('child_process').exec;

  String.prototype.extensionFromFilename = function() {
    return this.substr(this.split('.')[0].length + 1, this.length).toString();
  };

  String.prototype.filename = function() {
    return this.replace(/^.*[\/\\]/g, '');
  };

  String.prototype.filenameWithoutExtension = function() {
    return this.split('.')[0].toString();
  };

  Thumbbot = (function() {
    function Thumbbot(srcPath, destPath) {
      this.srcPath = srcPath;
      this.destPath = destPath;
      if (!this.destPath) {
        this.destPath = this.srcPath;
      }
      this.options = {
        x: 0,
        y: 0,
        width: null,
        height: null,
        method: 'resize',
        position: '00:00:01',
        viewport: {
          width: 1024,
          height: 768
        }
      };
    }

    Thumbbot.prototype.set = function(options) {
      var key, _results;
      _results = [];
      for (key in options) {
        _results.push(this.options[key] = options[key]);
      }
      return _results;
    };

    Thumbbot.prototype.handleImage = function(srcPath, destPath, callback) {
      var image,
       toWidth = this.options.width,
       toHeight = this.options.height,
       image = gm(srcPath);
      if (this.options.method === 'resize') {
        image.size(function (err,size){
          if( (toWidth && size.width>toWidth) || (toHeight && size.height>toHeight) && (toWdith || toHeight)) {
            //We need to resize
            image.resize(toWidth,toHeight).write(callback);
          }
          else {
            //We can take a short cut because it is already smaller than out interests
            fs.link(srcPath,destPath,callback);
          }
        });
        image.resizeTo(this.options.width, this.options.height, function() {
          if (callback) {
            return callback();
          }
        });
      }
      if (this.options.method === 'crop') {
        return image.cropFrom(this.options.x, this.options.y, this.options.width, this.options.height, function() {
          if (callback) {
            return callback();
          }
        });
      }
    };

    Thumbbot.prototype.snap = function(callback) {
      var cleanFilename, filename,
        _this = this;
      if (/^http/.test(this.srcPath)) {
        return exec("phantomjs " + __dirname + "/sh/render.js " + this.srcPath + " " + this.options.viewport.width + " " + this.options.viewport.height + " " + this.destPath, function() {
          return _this.handleImage(_this.destPath, _this.destPath, callback);
        });
      }
      switch (this.srcPath.extensionFromFilename()) {
        case 'png':
        case 'jpeg':
        case 'jpg':
        case 'gif':
          return this.handleImage(this.srcPath, this.destPath, callback);
        case 'mp4':
        case 'avi':
        case '3gp':
        case 'mov':
          return exec("ffmpeg -ss " + this.options.position + " -i " + this.srcPath + " -vframes 1 -y -f image2 " + this.destPath, function() {
            return _this.handleImage(_this.destPath, _this.destPath, callback);
          });
        case 'mp3':
        case 'aac':
        case 'wav':
          filename = this.srcPath.filename();
          cleanFilename = filename.filenameWithoutExtension();
          return googleImages.search(cleanFilename, function(err, images) {
            if (images[0]) {
              return images[0].writeTo(_this.destPath, function() {
                return _this.handleImage(_this.destPath, _this.destPath, callback);
              });
            } else {
              return callback(true);
            }
          });
        default:
          return callback(true);
      }
    };

    return Thumbbot;

  })();

  module.exports = Thumbbot;

}).call(this);
